print("wait ")
print ("Hello World")
print ("Hello World")
print ("Hello World")
print ("Hello World")
print ("Hello World")
print ("Hello World")
print ("Hello World")
print ("Hello World")
print ("Hello World")
