print("abhi")
print("AI")
print("ML")
print("DL")
print("wait ")
print ("Hello World")
print ("Hello World")
print ("Hello World")
print ("Hello World")
print ("Hello World")
print ("Hello World")
print ("Hello World")
print ("Hello World")
print("New branch")
print("3rd time change")
print("4th time change")
print("1234")


print ("aaisaaa nahiii karteeee !!!")

print("Humare yaha aisa hi hota hai")
print ("aaisaaa nahiii karteeee !!!")
print ("aaisaaa nahiii karteeee !!!")
print ("aaisaaa nahiii karteeee !!!")
print ("aaisaaa nahiii karteeee !!!")
print ("aaisaaa nahiii karteeee !!!")
print ("aaisaaa nahiii karteeee !!!")
print ("aaisaaa nahiii karteeee !!!")

print ("toh kesa hota he zara bataiyeee janabbb......")